### ISSUE TITLE
Polish translation!

### ISSUE THREAD

**Issue by RedtheNeko** [taragnor/city-of-mist#10]
Hello!

I really admire your work on City of Mist module! I would be honored if I could make full translation to Polish. I want to play with my friends, but they are not English-friendly.

I do not know coding and programing but I could make translation rightaway if you make ie. pl.json in translation section :)

Or just send you all by e-mail!

Best regres
Red

**Comment by taragnor** [comment]
If you've got a polish translation, I'd be more than happy to merge it into the system. Given I don't speak the language, it's not work I can do myself, but I welcome the contribution.

**Comment by RedtheNeko** [comment]
It's not complete 100% right now. I mostly worked on our (Polish published by Black Monk) STARTER SET. I would like to see how it looks and then complete the rest/make some corrections as time goes by.

{
ACTOR.TypeCharacter: "Bohater gracza",
ACTOR.TypeThreat: "Zagrożenie",
ACTOR.TypeCrew: "Ekipa",
ACTOR.TypeExtra: "Extra (Deprecated)",
ACTOR.TypeStorytagcontainer: "Składowisko tagów fabularnych",
ITEM.TypeTheme : "Motyw",
ITEM.TypeThemebook : "Zakładka",
ITEM.TypeTag : "Tag",
ITEM.TypeImprovement : "Rozwinięcie",
ITEM.TypeTag_question : "Pytanie do taga",
ITEM.TypeStatus : "Status",
ITEM.TypeClue : "Wskazówka",
ITEM.TypeJuice : "Esencja",
ITEM.TypeMove : "Ruch gracza",
ITEM.TypeGmmove : "Ruch MC",
ITEM.TypeSpectrum : "Spektrum zagrożenia",

CityOfMistTracker.trackerwindow.title: "Licznik odliczania",
CityOfMistTracker.trackerwindow.empty: "Umieść znacznik na scenie, aby rozpocząć odliczanie.",
CityOfMistTracker.trackerwindow.statuses: "Tatusy i tagi",
CityOfMistTracker.trackerwindow.status.addto: "Dodaj poziom statusu",
CityOfMistTracker.trackerwindow.status.subtract: "Odejmij poziom statusu",
CityOfMistTracker.trackerwindow.status.addnew: "Dodaj nowy status",
CityOfMistTracker.trackerwindow.status.permanent: "Permanentny status",
CityOfMistTracker.trackerwindow.status.temporary: "Tymczasowy status",
CityOfMistTracker.trackerwindow.status.delete: "Usuń status",

CityOfMistTracker.trackerwindow.tag.addnew: "Dodaj nowy tag fabularny",
CityOfMistTracker.trackerwindow.tag.permanent: "Permanentny tag",
CityOfMistTracker.trackerwindow.tag.temporary: "Tymczasowy tag",
CityOfMistTracker.trackerwindow.tag.delete: "Usuń tag fabularny",
CityOfMistTracker.trackerwindow.tag.storytag: "Tag fabularny",
CityOfMistTracker.trackerwindow.tag.burned: "Spal tag",

CityOfMist.terms.name: "Imię",
CityOfMist.terms.description: "Opis",
CityOfMist.terms.alias: "Pseudonim / Nazwa żetonu",
CityOfMist.terms.logos: "Logos",
CityOfMist.terms.mythos: "Mythos",
CityOfMist.terms.short_desc: "Krótki opis",
CityOfMist.terms.attention: "Skupienie",
CityOfMist.terms.crack: "Kryzys",
CityOfMist.terms.fade: "Zatracenie",
CityOfMist.terms.strike: "Cios",
CityOfMist.terms.mystery: "Sekret",
CityOfMist.terms.identity: "Tożsamość",
CityOfMist.terms.directive: "Dyrektywa",
CityOfMist.terms.theme: "Motyw",
CityOfMist.terms.themes: "Motywy",
CityOfMist.terms.status: "Status",
CityOfMist.terms.statuses: "Statusy",
CityOfMist.terms.newStatus: "Nowy status",
CityOfMist.terms.statusName: "Nazwa statusu",
CityOfMist.terms.spectrums: "Spektra",
CityOfMist.terms.themeTags: "Tagi motywu",
CityOfMist.terms.improvements: "Rozwinięcia",
CityOfMist.terms.tag: "Tag",
CityOfMist.terms.tags: "Tagi",
CityOfMist.terms.storyTags: "Tagi fabularne",
CityOfMist.terms.clue: "Wskazówka",
CityOfMist.terms.clues: "Wskazówki",
CityOfMist.terms.partialClue: "Częściowa wskazówka",
CityOfMist.terms.clueSource: "Źródło",
CityOfMist.terms.clueMethod: "Metoda",
CityOfMist.terms.clueAnswer: "Odpowiedź",
CityOfMist.terms.clueQuestion: "Pytanie",
CityOfMist.terms.juice: "Esencja",
CityOfMist.terms.help: "Pomoc",
CityOfMist.terms.hurt: "Zranienie",
CityOfMist.terms.MoEs: "Momenty przemiany",
CityOfMist.terms.bio: "Bio",
CityOfMist.terms.moves: "Ruchy",
CityOfMist.terms.coreMoves: "Ruchy podstawowe",
CityOfMist.terms.specialMoves: "Ruchy specjalne",
CityOfMist.terms.shb: "PRZESTAŃ. SIĘ. WSTRZYMYWAĆ.",
CityOfMist.terms.soft: "Miękkie",
CityOfMist.terms.softMove: "Ruch miękki",
CityOfMist.terms.softMoves: "Ruchy miękkie,
CityOfMist.terms.hard: "Twarde",
CityOfMist.terms.hardMove: "Ruch twardy",
CityOfMist.terms.hardMoves: "Ruchy twarde",
CityOfMist.terms.intrusion: "Wtrącenie",
CityOfMist.terms.intrusions: "Wtrącenia",
CityOfMist.terms.custom: "Niestandardowe",
CityOfMist.terms.customMove: "Niestandardowy ruch",
CityOfMist.terms.customMoves: "Niestandardowe ruchy",
CityOfMist.terms.enterScene: "Przy otwarciu sceny",
CityOfMist.terms.templates: "Szablony",
CityOfMist.terms.isTemplate: "Szablon?",
CityOfMist.terms.collectiveSize: "Rozmiar kolektywu",
CityOfMist.terms.activeExtraTheme: "Dodatkowy aktywny motyw",
CityOfMist.terms.MCEdit: "Do edycji MC",
CityOfMist.terms.customModifier: "Niestandardowy modyfikator",
CityOfMist.terms.mythosThemes: "Motywy Mythos",
CityOfMist.terms.logosThemes: "Motywy Logos",

CityOfMist.moves.genericFail: "Twardy ruch MC.",

CityOfMist.moves.CTG.name:"ZMIEŃ ZASADY GRY",
CityOfMist.moves.CTG.partial: "Otrzymujesz otrzymujesz punkty Esencji = Moc (minimum 1). Zużyj swój punkt Esencji, aby zyskać jeden z następujących efektów (1 za 1):",
CityOfMist.moves.CTG.success: "Otrzymujesz otrzymujesz punkty Esencji = Moc (minimum 2) oraz możesz zużyć punkt Esencji, aby:",
CityOfMist.moves.CTG.dynamite: "Otrzymujesz 3 punkty Esencji (+ Moc). Zużyj swój punkt Esencji, aby zyskać jeden z następujących efektów (1 za 1):",
CityOfMist.moves.CTG.0: "Stwórz tag fabularny.",
CityOfMist.moves.CTG.1: "Spal tag mocy lub tag fabularny.",
CityOfMist.moves.CTG.2: "Nadaj lub zredukuj status (jeden poziom za każdy punkt Esencji)",
CityOfMist.moves.CTG.3: "Eskalować efekt (większy zasięg lub więcej celów)",
CityOfMist.moves.CTG.4: "Przedłużyć efekt (wydłuż jego trwanie)",
CityOfMist.moves.CTG.5: "Ukryć efekt",
CityOfMist.moves.CTG.6: "Zyskać jakąkolwiek inną przewagę, którą ustalicie z MC",
CityOfMist.moves.CTG.7: "Efekt na dużą skalę",
CityOfMist.moves.CTG.8: "Permanentny efekt",
CityOfMist.moves.CTG.9: "Efekt ukryty we mgle",

CityOfMist.moves.convince.name:"PRZEKONAJ",
CityOfMist.moves.convince.partial:"Wybierz jeden z adekwatnych statusów z poziomem = Moc. Twój cel może przyjąć status lub trochę ci ustąpić, ale zachować swoją agendę.",
CityOfMist.moves.convince.success: "Wybierz jeden z adekwatnych statusów z poziomem = Moc. Twój cel może przyjąć status lub zmienić swoją agendę tak, by uwzględniała twój cel, przynajmniej na razie.",
CityOfMist.moves.convince.dynamite: "Choose a relevant status of tier PWR+2. Your target can choose either to take the status or change their agenda to include yours, at least for the time being. If the target gives in they also take a tier 2 temporary status  representing your influence. It can't be the same status as if they refused.",

CityOfMist.moves.FD.name: "ZMIERZ SIĘ Z ZAGROŻENIEM",
CityOfMist.moves.FD.fail: "Przyjmujesz pełen status.",
CityOfMist.moves.FD.partial: "Przyjmujesz status, ale z poziomem -1.",
CityOfMist.moves.FD.success: "Odpierasz efekt i nie uzyskujesz żadnego statusu.",
CityOfMist.moves.FD.dynamite: "Całkowicie odpierasz efekt, a następnie wybierasz 1:",
CityOfMist.moves.FD.0: "Odbijasz status na atakującego lub wykorzystujesz go na swoją korzyść. Atakujący otrzymuje wybrany przez Ciebie status z poziomem równym pierwotnemu.",
CityOfMist.moves.FD.1: "You bolster your defenses. You take an appropriate ongoing tier-1 status of your choice describing your improved defenses.",

CityOfMist.moves.GTTT.name: "STAŃ W SZRANKI",
CityOfMist.moves.GTTT.partial: "Wybierz 1",
CityOfMist.moves.GTTT.success: "Wybierz 2",
CityOfMist.moves.GTTT.dynamite: "Otrzymujesz wszystko poniższe",
CityOfMist.moves.GTTT.0: "Udaje ci się osiągnąć twój cel, np. zyskać coś, co było w posiadaniu przeciwnika.",
CityOfMist.moves.GTTT.1: "Nieźle dowalasz przeciwnikowi, nadając mu status z poziomem = Moc.",
CityOfMist.moves.GTTT.2: "Blokujesz, unikasz lub kontrujesz wszelkie starania przeciwnika. Jeśli tego nie wybierzesz, może on nałożyć na ciebie status. Jeśli przeciwnikiem jest BG, jego poziom = jego Moc.",

CityOfMist.moves.HWAYG.name: "UDERZ Z CAŁYCH SIŁ",
CityOfMist.moves.HWAYG.partial: "Po trafieniu nadajesz celowi wybrany status z poziomem = Moc (minimum 1). Wybierz 1:",
CityOfMist.moves.HWAYG.success: "Po trafieniu nadajesz celowi wybrany status z poziomem = Moc (minimum 1). Wybierz 2:",
CityOfMist.moves.HWAYG.dynamite: "Po trafieniu nadajesz celowi wybrany status z poziomem = Moc (minimum 1). Wybierz 1 z wybuchowej listy:",
CityOfMist.moves.HWAYG.0: "Kryjesz się lub zapewniasz sobie lepszą pozycję. Jeśli tego nie wybierzesz, cel może nałożyć na ciebie status. Jeśli jest to BG, jego poziom = jego moc.",
CityOfMist.moves.HWAYG.1: "Nieźle dowalasz przeciwnikowi lub dopadasz większą ich liczbę (+1 poziom).",
CityOfMist.moves.HWAYG.2: "Kontrolujesz przypadkowe szkody.",
CityOfMist.moves.HWAYG.3: "Utrzymujesz na sobie uwagę celu, jeśli to możliwe.",
CityOfMist.moves.HWAYG.4: "Zyskujesz przewagę. Weź 1 punkt Esencji. Możesz wykorzystać jak 'Zmień zasady gry'.",
CityOfMist.moves.HWAYG.5: "(Wybuch) Wybitny cios: Wybierz 3 z listy standardowych pozycji tego ruchu.",
CityOfMist.moves.HWAYG.6: "(Wybuch) Defend another: You protect both yourself and another ally from a counterstrike. The target of your attack cannot attack that ally on the target’s next move.",
CityOfMist.moves.HWAYG.7: "(Wybuch) Hit them hard: You hit them hard, increasing the tier of the status you give by two or hitting two more targets with the same status.",
CityOfMist.moves.HWAYG.8: "(Wybuch) Extreme collateral damage: everything and everyone around the target takes a status similar to the main status, with a tier equal to Power. This includes you or any allies, if you are nearby.",
CityOfMist.moves.HWAYG.9: "(Wybuch) Control the conflict: Take 2 Juice and you can use it to choose effect improvements from Change the Game.",

CityOfMist.moves.investigate.name: "ZBADAJ",
CityOfMist.moves.investigate.partial: "Otrzymujesz liczbę Wskazówek = Moc (minimum 1). Poświęć swoje Wskazówki (1 za 1), aby zadać MC pytanie na temat waszego śledztwa lub zadać innemu graczowi istotne pytanie dotyczące jego postaci. Muszą ci  udzielić odpowiedzi wprost lub dać ci solidną wskazówkę. Dodatkowo MC może wybrać jedno z poniższych:",
CityOfMist.moves.investigate.success: "Otrzymujesz liczbę Wskazówek = Moc (minimum 1). Poświęć swoje Wskazówki (1 za 1), aby zadać MC pytanie na temat waszego śledztwa lub zadać innemu graczowi istotne pytanie dotyczące jego postaci. Muszą ci  udzielić odpowiedzi wprost lub dać ci solidną wskazówkę.",
CityOfMist.moves.investigate.dynamite: "You get PWR clues. Your investigation reveals a key detail. The MC will reveal the most valuable detail in the scene that your investigation could reveal. You can then use your Clues to ask follow-up questions or other questions as usual.",
CityOfMist.moves.investigate.0: "Twoje dochodzenie naraża cię na niebezpieczeństwo.",
CityOfMist.moves.investigate.1: "Otrzymane wskazówki są niejasne, niekompletne lub częściowo prawdziwe, a częściowo fałszywe..",
CityOfMist.moves.investigate.2: "Osoba lub istota, której zadajesz pytanie, może zadać również jedno pytanie tobie. Odpowiadasz na tych samych warunkach.",

CityOfMist.moves.lookBeyond.name: "Look Beyond the Mist",

CityOfMist.moves.sneak.name: "DZIAŁAJ SKRYCIE",
CityOfMist.moves.sneak.partial: "Każdy, kto miał się nabrać na twoje sztuczki, faktycznie się na nie nabiera, ale MC wybiera 1 komplikację:",
CityOfMist.moves.sneak.success: "Każdy, kto miał się nabrać na twoje sztuczki, faktycznie się na nie nabiera.",
CityOfMist.moves.sneak.dynamite: "Your target is so entirely fooled by your secretive or deceptive actions that you can continue to move and/or act completely undetected by this target for the rest of the scene, so long as you do so in the same way you did when you scored 12 or more.",
CityOfMist.moves.sneak.0: "Ktoś mało istotny cię zauważa, ale to właśnie sprawia, że staje się ważny, prawda?",
CityOfMist.moves.sneak.1: "Zostajesz dostrzeżony tylko przez drugorzędny zmysł (ktoś wychwytuje twój zapach, gdy go śledzisz; ktoś dostrzega, że coś szepczesz, ale wiadomość nie jest słyszalna).",
CityOfMist.moves.sneak.2: "Musisz porzucić coś ważnego lub inaczej zostaniesz odkryty.",

CityOfMist.moves.TTR.name: "PODEJMIJ RYZYKO",
CityOfMist.moves.TTR.partial: "Robi się bałagan. MC postawi ci twarde warunki lub pozwoli wybrać mniejsze zło.",
CityOfMist.moves.TTR.success: "W jakiś sposób ci się udaje",
CityOfMist.moves.TTR.dynamite: "You pull it off spectacularly and even turn the situation to your advantage. Take 2 Juice and you can use it to choose effect improvements from Change the Game.",

CityOfMist.moves.SHB.significant.name: "PRZESTAŃ. SIĘ. WSTRZYMYWAĆ. (Znaczący)",
CityOfMist.moves.SHB.significant.fail: "DZIEJE SIĘ COŚ TRAGICZNEGO. Dodatkowo zaznacz Zatracenie/Kryzys i spal wszystkie tagi mocy na jednym z motywów.",
CityOfMist.moves.SHB.significant.partial: "Osiągasz dokładnie to, czego chciałeś + zaznacz Zatracenie/Kryzys i spal wszystkie tagi mocy na jednym z motywów.",
CityOfMist.moves.SHB.significant.success: "Osiągasz dokładnie to, czego chciałeś + zaznacz Zatracenie/Kryzys na jednym z motywów.",

CityOfMist.moves.SHB.noReturn.name: "PRZESTAŃ. SIĘ. WSTRZYMYWAĆ. (Bez odwrotu)",
CityOfMist.moves.SHB.noReturn.fail: "DZIEJE SIĘ COŚ TRAGICZNEGO. Dodatkowo wymień 1 z motywów.",
CityOfMist.moves.SHB.noReturn.partial: "Osiągasz dokładnie to, czego chciałeś + wymień jeden z motywów.",
CityOfMist.moves.SHB.noReturn.success: "Osiągasz dokładnie to, czego chciałeś + zaznacz Zatracenie/Kryzys i spal wszystkie tagi mocy na jednym z motywów.",

CityOfMist.moves.SHB.ultimate.name: "PRZESTAŃ. SIĘ. WSTRZYMYWAĆ. (Ostateczny)",
CityOfMist.moves.SHB.ultimate.fail: "DZIEJE SIĘ COŚ TRAGICZNEGO. Dodatkowo przyjmij status poziomu-6. Nie możesz użyć Ruchu Zmierz się z Zagrożeniem.",
CityOfMist.moves.SHB.ultimate.partial: "Osiągasz dokładnie to, czego chciałeś + zostajesz zabity, zniszczony lub na zawsze odmieniony (przynajmniej na razie). Przyjmij status poziomu-6. Nie możesz użyć Ruchu Zmierz się z Zagrożeniem.",
CityOfMist.moves.SHB.ultimate.success: "Osiągasz dokładnie to, czego chciałeś + wymień jeden z motywów.",

CityOfMist.moves.downtime.name: "PRZESTÓJ",
CityOfMist.moves.downtime.always: "Zawsze, gdy twoja postać może skorzystać z przestoju, wybierz jeden sposób na jego spędzenie:",
CityOfMist.moves.downtime.0: "Skup się na jednym ze swoich motywów Logos (lub dodatkowych). Powiedz wszystkim przy stole, jak to robisz, i zaznacz Skupienie na tym motywie.",
CityOfMist.moves.downtime.1: "Pracuj nad sprawą. Powiedz wszystkim przy stole, jak to robisz, i zdobądź 3 Wskazówki na podstawie swojego opisu.",
CityOfMist.moves.downtime.2: "Poznaj swój Mythos. Powiedz wszystkim przy stole, który Sekret chcesz odkryć i jak to robisz. Otrzymujesz 1 Wskazówkę na podstawie swojego opisu. Zaznacz Skupienie na motywie powiązanym z Sekretem.",
CityOfMist.moves.downtime.3: "Przygotuj się do następnej aktywności. Powiedz wszystkim przy stole, jak się przygotowujesz, i wybierz jedną opcję: odzyskaj wszystkie spalone tagi mocy LUB uzyskaj 3 punkty Esencji na podstawie swojego opisu. Możesz wybrać spośród ulepszeń efektu z Ruchu Zmień zasady gry.",
CityOfMist.moves.downtime.4: "Odzyskaj siły po ostatniej aktywności. W przypadku każdego trwającego statusu, który nadal ma na ciebie wpływ, MC powie ci, czy i jak można go zmniejszyć w czasie przestoju oraz o ile poziomów. Alternatywnie MC może pozwolić ci zmniejszyć jeden dowolny lub kilka z twoich statusów o jeden poziom za każdy adekwatny tag, który posiadasz.",

CityOfMist.moves.answers.name: "Finally, Some Answers",
CityOfMist.moves.answers.always: "When you find answers to your Mystery, choose one, two, or all three:",
CityOfMist.moves.answers.0: "You gain a deeper understanding of your Mythos, of the subject of your Mystery, or of the link between your Mystery and your Mythos. Mark Attention on the theme to which this Mystery belongs.",
CityOfMist.moves.answers.1: "You are shocked by the discovery to the point of rejecting your Mythos or an aspect of your ordinary life. Mark Fade or Crack on any theme.",
CityOfMist.moves.answers.2: "Your questions are answered. Choose a new Mystery for this theme.",

CityOfMist.moves.flashback.name: "Flashback",
CityOfMist.moves.flashback.always: "Once per session, when you have the spotlight, choose 1:",
CityOfMist.moves.flashback.0: "Describe an action carried out by your character in the past and make a move for that action. The outcome of the move affects the current scene.",
CityOfMist.moves.flashback.1: "Describe events from your character’s backstory that become relevant now. The MC can award you with 1 Juice or 1 Clue based on your description.",

CityOfMist.moves.foreshadowing.name: "Foreshadowing",
CityOfMist.moves.foreshadowing.miss: "You're safe for now. Your nemesis will not take part in the next session.",
CityOfMist.moves.foreshadowing.partial: "You can sense your nemesis is coming but you're not sure. The MC can choose whether to include your Nemesis in the next session or not. If she does, she does not get to make a surprise MC move.",
CityOfMist.moves.foreshadowing.success: "One of your Nemeses will overwhelm you or get the drop on you in the next session. When the MC introduces your nemesis, she also gets to make a move as if you missed a player move.",

CityOfMist.moves.hardchoice.name: "Make A Hard Choice",
CityOfMist.moves.hardchoice.0: "When answers to your Mystery are within reach, but you forego them, mark Fade on that Mystery’s theme.",
CityOfMist.moves.hardchoice.1: "When your Identity demands you act or speak in a given way and you don’t, mark Crack on that Identity’s theme.",
CityOfMist.moves.hardchoice.2: "When you sacrifice something you truly want in order to abide by your Identity, mark Attention on that Identity’s theme",

CityOfMist.moves.monologue.name: "Opening Monologue",
CityOfMist.moves.monologue.always: "At the beginning of every session, one player goes into a monologue as his or her character, relating the character’s thoughts and feelings at this point in the story.",

CityOfMist.moves.sessionEnd.name: "Session End",
CityOfMist.moves.sessionEnd.always: "At the end of the session, when the credit roll, go around the table. Each player can answer one or more of the following questions:",
CityOfMist.moves.sessionEnd.0: "How has the crew grown this session? Recover a burnt crew power tag or mark Attention on a crew theme.",
CityOfMist.moves.sessionEnd.1: "Which character had the most meaningful interaction with your character this session? Add one Help point or one Hurt point next to their name on your character card.",
CityOfMist.moves.sessionEnd.2: "Which of your themes is under the most strain? If it collapses, what new aspect will show up in its place? Write down the answer under FLIPSIDE on that theme’s card.",

CityOfMist.generic.narration: "Narracja",

CityOfMist.command.submit: "Zapisz",
CityOfMist.command.toggleLock: "Toggle Sheet Lock",
CityOfMist.command.narrationBox: "Narration Box",
CityOfMist.command.executeMove: "Wykonaj ruch",
CityOfMist.command.destroyTheme: "Zniszczony motyw",
CityOfMist.command.buildUpGained: "Build Up Points Gained",
CityOfMist.command.editClue: "Edytuj wskazówkę",
CityOfMist.command.addToJounral: "Dodaj do dziennika",
CityOfMist.command.askQuestion: "Zadaj pytanie",
CityOfMist.command.bankClue: "Bank Clue",
CityOfMist.command.refundClue : "Refund Clue",
CityOfMist.command.strikeout : "Toggle Modifier",

CityOfMist.message.rejectedQuestion : "Question Invalid for Method (Clue Refunded)",
CityOfMist.message.waitingPlayer : "Oczekiwanie na odpowiedź Gracza",
CityOfMist.message.waitingMC : "Oczekiwanie na odpowiedź MC",
CityOfMist.message.clueBanked : "banked",
CityOfMist.message.attentionAwarded: "+1 do skupienia",
CityOfMist.message.attentionManual: "Musisz dodać skupienie manualnie",

CityOfMist.misc.newMoE: "Nowe momenty przemiany",
CityOfMist.misc.reduceTier: "Obniż poziom statusu o 1",

CityOfMist.tooltip.gmmove: "Use [] around a word to make a status or tag. Using [a:name] will make a status auto-applied when the move is triggered. Using [i:name] will ignore collective bonus. [a,i:name] will do both."
}

**Comment by theczarek** [comment]
@RedtheNeko 
In string like "Wybierz jeden z adekwatnych statusów z poziomem = Moc. Twój cel może przyjąć status lub zmienić swoją agendę tak, by uwzględniała twój cel, przynajmniej na razie.", there is a variable PWR to use. If You put it in string it will give automatic power calculation in chat message. Check out english verison.

**Comment by RedtheNeko** [comment]
@theczarek I've made translation 1:1 can you show me where it is in EN version?

btw is there any chat/messenger/anything to talk or only here? :)

**Comment by theczarek** [comment]
> @theczarek I've made translation 1:1 can you show me where it is in EN version?
> 
> btw is there any chat/messenger/anything to talk or only here? :)

Sure - my discord: theczarek#8689 :)

For expample line 101 in en.json: 
"CityOfMist.moves.CTG.partial": "You get PWR Juice. Spend your Juice to gain the following effects, one-to-one:",

So if You chage Moc for PWR it will autocalculate Power. Also tere are other expresions line PWR2 and PWR3 (those are for cases when you get min 2 or min Power)

**Comment by RedtheNeko** [comment]
Also one question - is there any way to implement polish font? With all of the ę, ó, ą, ś, ł, ę etc? :D

**Comment by taragnor** [comment]
I will put in the stuff that was posted for next release. 

Polish font is definitely possible. Foundry uses unicode, so all characters should be valid.

**Comment by RedtheNeko** [comment]
@taragnor can I catch you on discord?! :D

Red_the_Neko#1516

**Comment by taragnor** [comment]
> @taragnor can I catch you on discord?! :D
> 
> Red_the_Neko#1516

Sent you a friend request.
