### ISSUE TITLE
Manifest is showing as INVALID

### ISSUE THREAD

**Issue by afalk** [taragnor/city-of-mist#17]
Tried to update this from your .json file but Foundry Chokes on it saying that it is invalid :O

**Comment by taragnor** [comment]
Not sure why that would be the case. It seems to install fine for me. Try uninstalling the system and reinstalling it.

**Comment by afalk** [comment]
Will do -- I'll update w/the response!

**Comment by afalk** [comment]
Uninstalled the Game System - then rebuilt the world (le sigh) -- enabled
modules very slowly LOL and we seem to be stable :D

Thanks,

Tony
