### ISSUE TITLE
weakness tag

### ISSUE THREAD

**Issue by a8418635** [taragnor/city-of-mist#20]
When I add a new weakness tag my improvement increases instead of diminishing

I'm not quite sure if this is correct

**Comment by taragnor** [comment]
Likely expected behavior. If it's your second weakness on a theme then you are permitted to take another power tag as per the CoM rules. So you should getting another advancement to take that power tag.

**Comment by a8418635** [comment]
The problem is that the third or fourth weakness tag will also give me an improvement  
I am now manually eliminating improvement

**Comment by taragnor** [comment]
Ah. I wasn't aware there was even a way within the rules to get a third or fourth weakness tag, thus I didn't bother coding a special exception for them. Basically any weakness tags beyond the first gives you an extra improvement.

**Comment by a8418635** [comment]
Improvement can add, change or reduce weakness tags 
Ok I understand
