### ISSUE TITLE
City of Mist world doesn't work after FoundryVTT v10

### ISSUE THREAD

**Issue by AbnormalFricker** [taragnor/city-of-mist#22]
Uncaught (in promise) Error: Version 10 Compatibility Failure
------------------------------------------------------------------------------------------
Several Document class definitions include properties which collide with the new V10 DataModel:
------------------------------------------------------------------------------------------
The CityActor class defines the "type" attribute which collides with the "type" key in the Actor data schema
The CityItem class defines the "type" attribute which collides with the "type" key in the Item data schema
    at Game.initializeDocuments (foundry.js:7858)
    at Game.setupGame (foundry.js:7789)
    at async Game._initializeGameView (foundry.js:8877)
![image](https://user-images.githubusercontent.com/113374410/189707290-bfd2ae20-82ff-4638-b5e1-cc68a2936dae.png)

**Comment by taragnor** [comment]
New version of CoM should be v10 Foundry compatible.
