### ISSUE TITLE
v10 manifest migration missing id and typo in relationships field

### ISSUE THREAD

**Issue by rikmarais** [taragnor/city-of-mist#24]
Hi there, nothing major here but the manifest is missing the `id` field specified in https://foundryvtt.com/article/manifest-migration-guide/
As such, it may fail certain migration or compatibility checks that rely on this field being present.

There is also a typo in the `relationships` field

https://github.com/taragnor/city-of-mist/blob/main/system.json

**Comment by taragnor** [comment]
Thank you for pointing that out, I'll fix that for the next release.

**Comment by amanwing** [comment]
Just want to mention that the version here still does not run on foundry. I donwloaded per hand and imported the zip. This is the error message from foundry: This World is using the Game System City of Mist. The system version currently installed is '2.5.0' which currently does not support Foundry VTT v10 Stable 1 (Build 286).
You will not be able to upgrade your World until the [Game System](https://eu.forge-vtt.com/bazaar#type=system&package=city-of-mist) has been installed or updated to a version which is compatible with the Foundry VTT v10 Stable 1 (Build 286).

**Comment by rikmarais** [comment]
@amanwing Yeah, the current version is still 2.5.0, @taragnor has not released a new version yet :)
