### ISSUE TITLE
Crispy tags are being  automatically burned

### ISSUE THREAD

**Issue by tadeucaldas** [taragnor/city-of-mist#27]
Everytime i use a movement as a player, tags that i´ve marked are being burned. Is it suppose to work that way? Maybe there is something into the gamebook guide that i missed.

Anyway.. thanks a lot for ur work! If u need an extra dev let me know!

**Comment by kiaen1** [comment]
If you specifically mean crispy tags, that is what is supposed to happen, yes. 
The rules for this are on page 215 of the Player's Guide, Heading "Tags in Crew and Extra Themes" Sub heading "Crew or Extra Power Tags".
Cripsy tags(Things like the crew, extra tags, etc) are burnt on usage.
![image](https://user-images.githubusercontent.com/96035276/198854358-bbcf8d5c-3deb-42ef-a7e5-3d0d1d7d032d.png)
Power tags from your core themes, shouldn't be marked as crispy.
![image](https://user-images.githubusercontent.com/96035276/198854343-70f63e73-5c92-42f3-a8a0-978a61e8b13b.png)
