### ISSUE TITLE
Theme Kits

### ISSUE THREAD

**Issue by kiaen1** [taragnor/city-of-mist#29]
There's currently not a good way to do/proper way to do theme kits. There are a couple ways to do a work-around theme kit.

You can do an item/Themebook(Picture 1), which lets you make a custom theme, and make that themebook the actors' extra theme, but three issues with this is that ![image](https://user-images.githubusercontent.com/96035276/198853668-0efa840e-4b76-41aa-96bd-90dab98cce9b.png)
1 - it shows up in the select theme window, when you wouldn't want it to show up there. (Picture 2)
![image](https://user-images.githubusercontent.com/96035276/198853704-ce490e73-297c-41f4-ae52-39e1bbbfa10d.png)
2- When you select your tags those are the "Questions" so you have to copy/paste the question into the answer, for the tag to show up as that name. (Pictures 3 & 4)
![image](https://user-images.githubusercontent.com/96035276/198853714-8286f10d-8391-423e-9803-8f54144cd8f3.png)
![image](https://user-images.githubusercontent.com/96035276/198853716-ac9298f6-7db8-42d9-b271-bcf7431a85bc.png)
3 - It either shows up as unamed theme, or "Extra theme name/Theme name" (Picture 5&6)
![image](https://user-images.githubusercontent.com/96035276/198853739-d3594efd-2652-4ded-ade7-34e025c73a79.png)
![image](https://user-images.githubusercontent.com/96035276/198853760-960ce47e-5599-47f1-9852-5dccd1ff6e1e.png)

or you can build the theme in the actor, as the extra theme. Which I don't like for a couple of reasons.
Using Das & Quinn from Nights of Payne Town as my example,
1 -  ALL of the theme improvements show up, AND you have to make a custom Compendium to add any custom "Improvements". Das & Quinn have 1 possible improvement "Sacrifice" and since that is a custom one, it doesn't show up in Improvements, but all base Ally theme improvements do.(Pictures 7, 8, & 9)(Or maybe a custom item improvement, but as I am a dumb dumb, I wasn't able to figure out how to make it show up as a selection)
![image](https://user-images.githubusercontent.com/96035276/198853785-cd84d23c-1a91-4124-a992-67758989763b.png)
![image](https://user-images.githubusercontent.com/96035276/198853791-3e37df0f-44cc-4edd-beb6-e46d7a1ad52b.png)
![image](https://user-images.githubusercontent.com/96035276/198853807-492e0eb9-da4d-420f-bfd3-5a91602240bc.png)
2 - There is no good way but a picture of the themekit from the book to show the possible tags they can choose.(Picture 10 & 11)
![image](https://user-images.githubusercontent.com/96035276/198853828-00db2db6-32d2-4abf-8273-6a13ffddc938.png)
![image](https://user-images.githubusercontent.com/96035276/198853837-32192092-524f-4006-baa0-94677442055b.png)

I have an idea of making an Actor type called "Theme kit" That you would put in the Power tags, weakness tags, improvements, name of the tag, and the type of theme it is,(Kinda like the same UI as the Custom Themebook) since Shadows and showdowns gives us a way to make theme that isn't just extra themes.
You could then give ownership of the Theme kit actor like you do now for extra themes, but instead of the question page, you just get the pre-selected answers for power tags/weakness tags, and improvements.

If my suggestion of the way to do it doesn't quite make sense I can attempt to make a very bad/basic implementation of it to show what I mean.

**Comment by taragnor** [comment]
Yeah, Themekits have been on my list of things I'd like to implement at some point. They just haven't made it in yet.

Right now you're correct that support for them isn't great. 

Eventually when I do implement them, they'll probably be a separate "Theme Kit" Item that the theme will point to instead of a regular Themebook, that'd just take some coding to do so, so I haven't gotten around to it.

Potentially after I'm done with getting rid of existing bugs and getting things running in Foundry v10, I'll relook at adding that capability.

**Comment by kiaen1** [comment]
... I might of started on that idea, too bad I'm not great at programming/coding. 

But that's pretty much the exact idea I had. _If_ I do end up actually getting one made, and it's before you do it, I'll make a fork for it to let you see/submit a pull request, if needed.

Thank you for getting back to me, and thank you for all the work you put into this!

Gonna go ahead and mark it as closed, as you are (obviously) aware, and have it in mind!
