### ISSUE TITLE
Sheet Redesign

### ISSUE THREAD

**Issue by Galdormin** [taragnor/city-of-mist#3]
Nice work on the City of Mist rules set.

I made some changes on the **player character** and **threat** sheets to make it prettier but also more readable. I considered age and residence as minor information for a header, I added the logos and a short physical description. The headers can be modified when the sheet is not locked.

![PC-sheet](https://user-images.githubusercontent.com/76685550/134812063-3b4c8e0b-438d-4f99-a69b-b9efd0c963e3.png)

![threat-sheet](https://user-images.githubusercontent.com/76685550/134812076-d4f4f38a-4ef6-4567-908e-3ec38992542c.png)

If you have any changes or additions don't hesitate to let me know Galdormin#6561 (on discord). If it suits you, we could add directly the sheets (when they will be finished) to the system.

**Comment by taragnor** [comment]
Those look to be pretty good changes. I'll see to implementing them. Just got some free time recently to put some more work into it, so I'll put that on my list of extra changes.

**Comment by Galdormin** [comment]
I already made these modifications for a personal campaign. I just made a pull-request with what I did.
