### ISSUE TITLE
The option for "Broad Tag" has been removed, while the function remains.

### ISSUE THREAD

**Issue by NikolaSama** [taragnor/city-of-mist#35]
Unsure, if the option was removed purposefully, but since a few updates back, I can no longer tick a tag to be "Broad", while it still shows the icon to older tags that I had set to that.
![Screenshot 2022-12-20 132924](https://user-images.githubusercontent.com/6267543/208656745-067b0c08-9218-4f58-8af1-002ded585eba.png)

**Comment by taragnor** [comment]
Thanks for pointing this out. It's a bug. It will be fixed in the next release.
