### ISSUE TITLE
Option to disable "Add 3 attention, when adding weakness"

### ISSUE THREAD

**Issue by NikolaSama** [taragnor/city-of-mist#36]
As per the rules of the book, when a character gains and improvement, they can choose to add a Weakness Tag to a theme. This is a full improvement by itself, but the sheet treats every addittion of a weakness as if it's during "character creation", where taking a 2nd weakness gives you an extra power tag.

Considering the different ways Weakness Tag adding/deleting/changing affects the theme improvements, I'd appreciate a promt, maybe, when you add/delete a weakness tag? Or just an option to disable auto-attention giving from adding a weakness tag.

**Comment by taragnor** [comment]
Sounds like a good idea. I'll put it on my list of future features to implement.
