### ISSUE TITLE
v11 Upgrade

### ISSUE THREAD

**Issue by lorthirk** [taragnor/city-of-mist#45]
Hello,

I just bought Foundry VTT to play City of Mist on it, but I noticed that the current plugin only supports Foundry v10. Is there any plan to upgrade to v11? Did you already had a look at possible breaking changes?

**Comment by taragnor** [comment]
Version 2.6.7 is released which should be v11 compatible. Though it hasn't been extensively tested. So let me know if there are any v11 specific problems.
