### ISSUE TITLE
Unable to create Scene Tags or Statuses

### ISSUE THREAD

**Issue by JasonSunday** [taragnor/city-of-mist#49]
When I click on the Scene widget to create Scene Tag or Status nothing happens except errors in the console on V11 build 307.

![FoundryVtt-CoM-error](https://github.com/taragnor/city-of-mist/assets/10623958/7c1f2d0d-c723-49ed-913e-8610601ae99a)

**Comment by taragnor** [comment]
This issue should be fixed in version 2.6.9
