### ISSUE TITLE
Character Sheet Stops Functioning 

### ISSUE THREAD

**Issue by Xyxzor** [taragnor/city-of-mist#5]
Had a strange issue during a session tonight where one of the character sheets stopped working. It was not executing moves for either the player or myself. Saw this in the inspector. 
![CityOfMist_CharacterError](https://user-images.githubusercontent.com/87257241/144002316-48fc9f77-6d0c-49f7-826e-a728f3b11782.png)

**Comment by taragnor** [comment]
Thanks for the bug report, I will look into it.

**Comment by Xyxzor** [comment]
If repro is tricky let me know, and I can try and provide access to the world.

**Comment by taragnor** [comment]
> If repro is tricky let me know, and I can try and provide access to the world.

Yeah, I was not able to reproduce. 

Do you have steps to reproduce, or can you email me the world file where it has the bugged data?

**Comment by taragnor** [comment]
Bug has been fixed as of version 2.3.4
