### ISSUE TITLE
Emhamced Actor Directory option is not working.

### ISSUE THREAD

**Issue by NikolaSama** [taragnor/city-of-mist#52]
![image](https://github.com/taragnor/city-of-mist/assets/6267543/55a752cf-cf98-404d-96ff-e4fd659f8f6d)
![image](https://github.com/taragnor/city-of-mist/assets/6267543/17567fd5-add0-419a-84f5-b0aa80ef1d6e)
Tested without modules, so seems to be a bug.

**Comment by taragnor** [comment]
This is the intended behavior. The idea is that the MC is allowed to keep the NPCs true name from the players if they want, and could list them under the alias. The alias is what the players know the NPC as, which may or may not be the truth.

**Comment by NikolaSama** [comment]
Ah, pardon. Got used to seeing both names. Found it handy, but if it's meant like this, then all good.
