### ISSUE TITLE
Visibility of pips

### ISSUE THREAD

**Issue by imiri78** [taragnor/city-of-mist#56]
Make pips and their progression more visible to MC and players.
As of now version 2.7.1 it is possible to see the pips of a status as a tooltip if one hovers over a bold status on the character sheet, the tooltip of a token in an active scene and the status tracker of the scene.

If the status itself does not change the players might not notice the effect the move had and that the increse of the status is closer.

Writing it as status-pips or status and a number of stars like 3** would make the progress more visible.
<img width="150" alt="com3" src="https://github.com/taragnor/city-of-mist/assets/66552178/e3e1aff2-b609-404b-b495-26db2d5de51f">
<img width="188" alt="com2" src="https://github.com/taragnor/city-of-mist/assets/66552178/644ab098-b042-479c-acd9-521edff8697b">
<img width="294" alt="com1" src="https://github.com/taragnor/city-of-mist/assets/66552178/23da98dc-102c-46ed-b1f7-e97162167122">

**Comment by taragnor** [comment]
I added a new setting as of 3.0.0 that allows changing of how pips are displayed.
