### ISSUE TITLE
BUG: Character sheets are completely ruined

### ISSUE THREAD

**Issue by Eggh3d** [taragnor/city-of-mist#60]
Self explanatory, the character sheets have been completely ruined and I can no longer MC my game because of it. Attention and moments of evolution are completely stripped from the character sheet, and to some of my players the character sheets don't even register as a card deck like they should. Please fix this soon as I won't have a session until this is fixed.
![image_2024-04-09_184244722](https://github.com/taragnor/city-of-mist/assets/166567884/f5d6905c-4133-40c4-be30-fca48f8e188d)
![image_2024-04-09_184305269](https://github.com/taragnor/city-of-mist/assets/166567884/fef7a285-b5ff-4965-932c-32e092987999)

**Comment by taragnor** [comment]
Attention and moments of evolution are now on the back of the card. click the text at the top of the card to flip it. MoE are behind the story tags and status card, which can also be flipped. 

Not sure what's wrong with the sheet that's totally broken. Would need more details there.

**Comment by Eggh3d** [comment]
> Attention and moments of evolution are now on the back of the card. click the text at the top of the card to flip it. MoE are behind the story tags and status card, which can also be flipped.
> 
> Not sure what's wrong with the sheet that's totally broken. Would need more details there.

This is all of the information I have, this is only player side, I as an MC cannot see it. Making a new sheet does not work, I cannot switch to the default sheet at all. Their roles and permissions are in order and match the ones of someone with a functioning character sheet.  Everything else is a complete unknown to me.

**Comment by taragnor** [comment]
> This is all of the information I have, this is only player side, I as an MC cannot see it. Making a new sheet does not work, I cannot > switch to the default sheet at all. Their roles and permissions are in order and match the ones of someone with a functioning 
> character sheet. Everything else is a complete unknown to me.

So just one player has the completely bugged sheet and it works for everyone else? And you're able to open their sheet, but they cannot on their own?

**Comment by Eggh3d** [comment]
> > This is all of the information I have, this is only player side, I as an MC cannot see it. Making a new sheet does not work, I cannot > switch to the default sheet at all. Their roles and permissions are in order and match the ones of someone with a functioning
> > character sheet. Everything else is a complete unknown to me.
> 
> So just one player has the completely bugged sheet and it works for everyone else? And you're able to open their sheet, but they cannot on their own?

For all players except one the sheets are completely bugged, when I open their sheets they work as intended but for them it doesn't work at all, and looks like pic above.

**Comment by Eggh3d** [comment]
Am I able to please get the old manifest url for 3.0.1? All of the older versioned manifest urls are the exact same as 3.0.2 on the Foundry website.

**Comment by Eggh3d** [comment]
I managed to get an older version of city of mist from a friend and my stuff is working fine now. I strongly encourage you to not replace the old manifest urls with the current version and to please fix that if at all possible. Thank you for taking the time to interact with this report.

**Comment by taragnor** [comment]
3.0.1 should be the same as 3.0.2, since 3.0.2 was just an extra version number to get CoM to work with the forge, so I don't know if that'll help you. 

This manifest should work for 3.0.1 (I'm not 100% sure on this since I've never tried installing from an old manifest): https://raw.githubusercontent.com/taragnor/city-of-mist/v.3.0.1/src/city-of-mist/system.json

If you're looking to totally regress to 2.7.1, which should be fully stable for older campaign files, you can try:
https://raw.githubusercontent.com/taragnor/city-of-mist/v.2.7.1/system.json

Right now unfortunately I don't have enough information to know what's causing your issue with the character sheets. I've been unable to duplicate it with my own testing.
