### ISSUE TITLE
After update to v3.XX all danger spectrum revert to 1

### ISSUE THREAD

**Issue by theczarek** [taragnor/city-of-mist#63]
As in title. 
![image](https://github.com/taragnor/city-of-mist/assets/83540404/f47c5378-1b17-4fca-affc-c17f6cbd450b)

Right now it's propbably irreversible. But it would be nice to have proper migration after another big update. I've got extesive danger libary (including mos of MC guidbook stuff) redoing it in the middle of campaing is pain :/.

**Comment by taragnor** [comment]
Sorry about that. 

I added a migration fix in the latest version, it should reverse the so long as you haven't edited the spectrum since the update.
