### ISSUE TITLE
Edits in one actor affects other actors.

### ISSUE THREAD

**Issue by ShadowyXP** [taragnor/city-of-mist#64]
When other players edit text fields or add and delete items on sheets, it refreshes all actors, and not just the actor being edited.

To reproduce.

* Create two actors
* Login with two browser windows on separate actors.
* Focus a text field in actor 1 (mystery/identity, or theme name)
* In actor two, add or delete a theme/tag. It will reset and unfocus the text field for actor 1.

**Comment by ShadowyXP** [comment]
In situations where multiple players are making characters together, it is a nightmare where people cant reliably edit anything on their own without it being erased due to someone else making an edit.

**Comment by taragnor** [comment]
This should be fixed now. At least in cases where it can be. The crew theme being edited will have to update all actor sheets that depend on it, but PCs or dangers changing should no longer have any effect. This was a holdover from back when the PC sheets listed all the tags in the nearby scene, which caused it to look at all the other nearby sheets, and have to adapt when one changed.
