### ISSUE TITLE
Moment of Evolution Tracking?

### ISSUE THREAD

**Issue by NamelessOccasion** [taragnor/city-of-mist#70]
Apologies if this has been covered, couldn't see it in other threads and didn't know where else to ask. Are moments of Evolution manually tracked? I can see in older versions of the sheet there was a tab (this was on a youtube video specifically), but even when cracking themes and seeing the chat box that states the points, I can't see if this is tracked anywhere. Is this manually tracked now? 

Apologies if I am just being stupid and not turning on a setting or not seeing it somewhere!

**Comment by imiri78** [comment]
![image](https://github.com/user-attachments/assets/286916ef-b4f8-452d-a7ca-a321c709cda2)
![image](https://github.com/user-attachments/assets/1d6a75a2-39d9-4d45-82e8-0a518043ebea)

You can flip the story tags and statuses card by clicking the title to see buildup points and moments of evolution. Most card now hav a flipside.

**Comment by NamelessOccasion** [comment]
Oh my god, thanks so much! 
I thought I had tried all the reverse sides, thanks for pointing to that one!
